{{- if .Values.pullSecret.enabled -}}
{{- $app := .Values.pullSecret -}}
{{- $ns := .Values.namespace.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $app.name }}
  namespace: {{ $ns }}
data:
  .dockerconfigjson: {{ $app.value }}
type: kubernetes.io/dockerconfigjson
{{- end }}